### ISSUE TITLE
一起看问题请教

### ISSUE THREAD

**Issue by lijunshuo** [guyijie1211/JustLive-Api#6]
yijie大佬您好，我可否请教你个问题呢，最近我在调测这个虎牙的一起看无法播放的问题，我发现这个getUrlTest函数根据platform和roomid会返回一个m3u8的地址，这个m3u8是个什么原理呢
<img width="864" alt="截屏2022-06-12 下午8 07 43的副本" src="https://user-images.githubusercontent.com/47944281/173232539-5312f1b0-0d9b-4354-ab65-ca3e3533b0c2.png">

因为我看这个项目参考的python项目 [wbt5/real-url](https://github.com/wbt5/real-url) ，我跑了一下这个项目的脚本，我发现反悔的直播间地址是这样子的，这个m3u8地址和这个地址有什么联系吗，yejie大佬可否赐教一下，谢谢！！！
<img width="747" alt="截屏2022-06-12 下午8 14 35" src="https://user-images.githubusercontent.com/47944281/173232643-3e2cc184-6215-4e55-9e33-4a6a286cdbc5.png">

**Comment by guyijie1211** [comment]
font{
        line-height: 1.6;
    }
    ul,ol{
        padding-left: 20px;
        list-style-position: inside;
    }


    
    real_url里的一起看地址放不了的，虎牙一起看的源似乎都有特殊的加密方式。我这里用的是另外一个项目rain-dl/real-url-proxy-server里的方式，这里返回的是我在服务器上部署的python进程的端口。但是现在用这个项目返回的地址似乎也不行了
    
        
            
        
    
    
     
    
        
                    ***@***.***
        
    
 

    在2022年6月12日 ***@***.***> 写道： 



yijie大佬您好，我可否请教你个问题呢，最近我在调测这个虎牙的一起看无法播放的问题，我发现这个getUrlTest函数根据platform和roomid会返回一个m3u8的地址，这个m3u8是个什么原理呢

因为我看这个项目参考的python项目 wbt5/real-url ，我跑了一下这个项目的脚本，我发现反悔的直播间地址是这样子的，这个m3u8地址和这个地址有什么联系吗，yejie大佬可否赐教一下，谢谢！！！

**Comment by lijunshuo** [comment]
原来是这样子呀，那大佬我发现了一个可用的huya python代码，要不麻烦你看看能不能部署上去，我自己试了一下是没问题的
https://github.com/wbt5/real-url/issues/331#issuecomment-1133517617
